/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xx.h"



int main(void)
{
	RCC->APB2ENR |=(1<<4);       // Enable the GPIOC clock
	GPIOC->CRH	 = 0x44444445;  // Setting the Port C 8th pin as Output
	RCC->CR      =0x00000083;   //Selecting the HSI Clock


	SetSysClockAs8MHz();

	Tim3config();

	while(1)
	{
		GPIOC->BSRR |=(1<<8);		//Set the PC_8 pin
		delay(1000);
		GPIOC->BSRR |=(1<<24);		//ReSet the PC_8 pin
		delay(1000);

	}
}

